########################################
#
# define scoring mesh
#
/score/create/boxMesh boxMesh_1
#
/score/mesh/boxSize 100. 100. 100. cm
/score/mesh/nBin 1 1 1
#
/score/quantity/H10 testPSH10 Sv
###/score/filter/particle Filter gamma
/score/filter/particle Filter neutron
#
/score/close
#
/score/list
#
########################################
#
#/vis/disable
###/control/verbose 2
###/run/verbose 1
###/event/verbose 1
###/tracking/verbose 1
###/gun/particle neutron
###/gun/particle gamma
#/gun/energy 1.50e+02 MeV
/run/beamOn 600
#/vis/enable
#
########################################
#
# Dump scores to a file
#
/score/dumpQuantityToFile boxMesh_1 testPSH10 testresult.txt
#
#
